
name: bayestracking
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: L-CAS Bayestracking
description: |
  This build a bayestracking library

grade: devel
confinement: devmode

parts:
  ros-tutorials:
    source: https://github.com/LCAS/bayestracking.git
    source-branch: kinetic-devel
    plugin: catkin
    rosdistro: master
    source-space: bayestracking/
    catkin-packages: [bayestracking]
